server:
  port: 8081
spring:
  application:
    name: "auth"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://idp.example.com/issuer"
          client-id: "myclientid"
jwt:
  secret: "k+pS6L8A/3t5Xv9zQ8B7c6G2fI4Ea0N1mJ3hU5sR7yI="
  expiration: 3600
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs  # sigue siendo el endpoint interno de openapi
  swagger-ui:
    enabled: true
    url:  /openapi/swagger.yaml   # aquí se usa el archivo estático
    path: /swagger-ui.html

routes:
  paths:
    users: "/api/v1/users"
    usersByEmail: "/api/v1/users/{email}"
    usersById: "/api/v1/users/{idNumber}"

# --- Configuración Reactiva para PostgreSQL con R2DBC ---
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: auth
    username: postgres
    password: admin